package invoice

import (
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
)

type Client struct {
	AppId          string
	ConnectionHost string
}

func NewClient(appId string) *Client {
	return &Client{
		AppId: appId,
	}

}

func (c *Client) CheckMobilePhoneExist(code string) (bool, error) {

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	// TODO: This is insecure; use only in dev environments.
	host := HOST_VC_EINVOICE
	tr := &http.Transport{
		TLSClientConfig: &tls.Config{
			// InsecureSkipVerify: true
			ServerName: host,
		},
	}
	client := &http.Client{Transport: tr}
	params := url.Values{}
	params.Add("version", "1.0")
	params.Add("action", "bcv")
	params.Add("barCode", code)
	params.Add("TxID", "1.0")
	params.Add("appId", c.AppId)

	body := strings.NewReader(params.Encode())

	hostname := host

	if c.ConnectionHost != "" {
		hostname = c.ConnectionHost

	}

	req, err := http.NewRequest("POST", "https://"+hostname+"/BIZAPIVAN/biz", body)
	if err != nil {
		// handle err
		return false, fmt.Errorf("new request: %q", err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := client.Do(req)
	if err != nil {
		return false, fmt.Errorf("client connection: %q", err)
	}
	defer resp.Body.Close()
	data, _ := ioutil.ReadAll(resp.Body)

	dataMap := map[string]interface{}{}
	json.Unmarshal(data, &dataMap)
	// fmt.Println(string(data), dataMap)

	isExist, ok := dataMap["isExist"].(string)
	if !ok {
		return false, fmt.Errorf("isExist field missing")
	}

	return isExist == "Y", nil
}
